name: astrall
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^0.4.0+6
  firebase_auth: ^0.11.1+7
  firebase_storage: ^3.0.2
  cloud_firestore: ^0.12.5+2
  onesignal_flutter: ^3.0.0
  provider: ^6.0.0
  google_sign_in: ^5.1.0
  smooth_star_rating: ^1.1.1
  url_launcher: ^6.0.10
  brasil_fields: ^1.1.4
  material_design_icons_flutter: ^4.0.5955
  mercado_pago_mobile_checkout: ^0.1.0
  http: ^0.13.0
  image_picker: ^0.8.3+1
  intl: ^0.17.0
  permission_handler: ^8.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/imagens/

  fonts:
    - family: Rosario
      fonts:
        - asset: fontes/Rosario-Regular.ttf

    - family: Norwester
      fonts:
        - asset: fontes/norwester.otf

    - family: Montserrat
      fonts:
        - asset: fontes/Montserrat-Regular.ttf

    - family: Mokoto
      fonts:
        - asset: fontes/Mokoto.ttf

    - family: Anton
      fonts:
        - asset: fontes/Anton-Regular.ttf
